export let ActionTypes = {
  CLICK_JOURNAL: Symbol('CLICK_JOURNAL'),
  CREATE_NOTE: Symbol('CREATE_NOTE'),
  CREATE_HASH_TAG: Symbol('CREATE_HASH_TAG'),
  CREATE_TODO: Symbol('CREATE_TODO'),
  COMPLETE_TODO: Symbol('COMPLETE_TODO'),
  UNDO_TODO: Symbol('UNDO_TODO')
};
